// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { create, delete_, getById, getUserInfo, list, login, logout, type Options, refreshToken, register, update } from '../sdk.gen';
import type { CreateData, CreateError, CreateResponse, DeleteData, DeleteError, DeleteResponse, GetByIdData, GetByIdError, GetByIdResponse, GetUserInfoData, GetUserInfoError, GetUserInfoResponse, ListData, ListError, ListResponse, LoginData, LoginError, LoginResponse, LogoutData, LogoutError, LogoutResponse, RefreshTokenData, RefreshTokenError, RefreshTokenResponse, RegisterData, RegisterError, RegisterResponse, UpdateData, UpdateError, UpdateResponse } from '../types.gen';

/**
 * Supprimer une tâche
 *
 * Supprime définitivement une tâche appartenant à l'utilisateur authentifié.
 */
export const deleteMutation = (options?: Partial<Options<DeleteData>>): UseMutationOptions<DeleteResponse, AxiosError<DeleteError>, Options<DeleteData>> => {
    const mutationOptions: UseMutationOptions<DeleteResponse, AxiosError<DeleteError>, Options<DeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await delete_({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getByIdQueryKey = (options: Options<GetByIdData>) => createQueryKey('getById', options);

/**
 * Récupérer une tâche par son id
 *
 * Retourne les détails d'une tâche appartenant à l'utilisateur authentifié.
 */
export const getByIdOptions = (options: Options<GetByIdData>) => queryOptions<GetByIdResponse, AxiosError<GetByIdError>, GetByIdResponse, ReturnType<typeof getByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getByIdQueryKey(options)
});

/**
 * Modifier une tâche existante
 *
 * Met à jour les champs d'une tâche appartenant à l'utilisateur authentifié.
 */
export const updateMutation = (options?: Partial<Options<UpdateData>>): UseMutationOptions<UpdateResponse, AxiosError<UpdateError>, Options<UpdateData>> => {
    const mutationOptions: UseMutationOptions<UpdateResponse, AxiosError<UpdateError>, Options<UpdateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await update({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listQueryKey = (options?: Options<ListData>) => createQueryKey('list', options);

/**
 * Lister les tâches de l'utilisateur connecté
 *
 * Retourne les tâches de l'utilisateur authentifié avec filtrage optionnel par statut et recherche textuelle (titre + description).
 */
export const listOptions = (options?: Options<ListData>) => queryOptions<ListResponse, AxiosError<ListError>, ListResponse, ReturnType<typeof listQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await list({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listQueryKey(options)
});

/**
 * Créer une nouvelle tâche
 *
 * Crée une tâche rattachée à l'utilisateur authentifié.
 */
export const createMutation = (options?: Partial<Options<CreateData>>): UseMutationOptions<CreateResponse, AxiosError<CreateError>, Options<CreateData>> => {
    const mutationOptions: UseMutationOptions<CreateResponse, AxiosError<CreateError>, Options<CreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await create({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Enregistrer un nouvel utilisateur
 *
 * Crée un compte utilisateur. Endpoint public.
 */
export const registerMutation = (options?: Partial<Options<RegisterData>>): UseMutationOptions<RegisterResponse, AxiosError<RegisterError>, Options<RegisterData>> => {
    const mutationOptions: UseMutationOptions<RegisterResponse, AxiosError<RegisterError>, Options<RegisterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await register({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Rafraîchir le token d'accès
 *
 * Génère un nouveau access token à partir d'un refresh token valide.
 */
export const refreshTokenMutation = (options?: Partial<Options<RefreshTokenData>>): UseMutationOptions<RefreshTokenResponse, AxiosError<RefreshTokenError>, Options<RefreshTokenData>> => {
    const mutationOptions: UseMutationOptions<RefreshTokenResponse, AxiosError<RefreshTokenError>, Options<RefreshTokenData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await refreshToken({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Déconnecter l'utilisateur
 *
 * Invalide le refresh token côté serveur.
 */
export const logoutMutation = (options?: Partial<Options<LogoutData>>): UseMutationOptions<LogoutResponse, AxiosError<LogoutError>, Options<LogoutData>> => {
    const mutationOptions: UseMutationOptions<LogoutResponse, AxiosError<LogoutError>, Options<LogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await logout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Authentifier un utilisateur
 *
 * Retourne un access token JWT et un refresh token. Endpoint public.
 */
export const loginMutation = (options?: Partial<Options<LoginData>>): UseMutationOptions<LoginResponse, AxiosError<LoginError>, Options<LoginData>> => {
    const mutationOptions: UseMutationOptions<LoginResponse, AxiosError<LoginError>, Options<LoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await login({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getUserInfoQueryKey = (options?: Options<GetUserInfoData>) => createQueryKey('getUserInfo', options);

/**
 * Récupérer les informations de l'utilisateur connecté
 *
 * Retourne le profil de l'utilisateur authentifié.
 */
export const getUserInfoOptions = (options?: Options<GetUserInfoData>) => queryOptions<GetUserInfoResponse, AxiosError<GetUserInfoError>, GetUserInfoResponse, ReturnType<typeof getUserInfoQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUserInfo({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUserInfoQueryKey(options)
});
