// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:7000' | (string & {});
};

export type CustomApiResponseObject = {
    success?: boolean;
    message?: string;
    code?: number;
    data?: {
        [key: string]: unknown;
    };
};

export type TaskRequest = {
    title?: string;
    description?: string;
    status: 'BACKLOG' | 'TODO' | 'IN_PROGRESS' | 'IN_REVIEW' | 'BLOCKED' | 'ON_HOLD' | 'DONE' | 'CANCELLED';
};

export type Task = {
    id?: string;
    createdAt?: string;
    updatedAt?: string;
    title?: string;
    description?: string;
    status?: 'BACKLOG' | 'TODO' | 'IN_PROGRESS' | 'IN_REVIEW' | 'BLOCKED' | 'ON_HOLD' | 'DONE' | 'CANCELLED';
};

export type ApiResponse = {
    [key: string]: unknown;
};

export type UserRegisterRequest = {
    fullName?: string;
    username?: string;
    password?: string;
};

export type CustomApiResponse = {
    success?: boolean;
    message?: string;
    code?: number;
    data?: {
        [key: string]: unknown;
    };
};

export type LogoutAndRefreshRequest = {
    token?: string;
};

export type JwtAuthenticationResponse = {
    token?: string;
    refreshToken?: string;
    expiryToken?: string;
};

export type UserLoginRequest = {
    username?: string;
    password?: string;
};

export type User = {
    id?: string;
    createdAt?: string;
    updatedAt?: string;
    username?: string;
    fullName?: string;
    role?: 'GUEST_USER';
};

export type DeleteData = {
    body?: never;
    path: {
        /**
         * Identifiant unique de la tâche à supprimer (UUID)
         */
        id: string;
    };
    query?: never;
    url: '/api/tasks/{id}';
};

export type DeleteErrors = {
    /**
     * Bad Request
     */
    400: CustomApiResponseObject;
    /**
     * Utilisateur non authentifié
     */
    401: ApiResponse;
    /**
     * Tâche introuvable
     */
    404: ApiResponse;
    /**
     * Not Acceptable
     */
    406: CustomApiResponseObject;
    /**
     * Internal Server Error
     */
    500: CustomApiResponseObject;
};

export type DeleteError = DeleteErrors[keyof DeleteErrors];

export type DeleteResponses = {
    /**
     * Tâche supprimée
     */
    200: ApiResponse;
};

export type DeleteResponse = DeleteResponses[keyof DeleteResponses];

export type GetByIdData = {
    body?: never;
    path: {
        /**
         * Identifiant unique de la tâche (UUID)
         */
        id: string;
    };
    query?: never;
    url: '/api/tasks/{id}';
};

export type GetByIdErrors = {
    /**
     * Bad Request
     */
    400: CustomApiResponseObject;
    /**
     * Utilisateur non authentifié
     */
    401: ApiResponse;
    /**
     * Tâche introuvable
     */
    404: ApiResponse;
    /**
     * Not Acceptable
     */
    406: CustomApiResponseObject;
    /**
     * Internal Server Error
     */
    500: CustomApiResponseObject;
};

export type GetByIdError = GetByIdErrors[keyof GetByIdErrors];

export type GetByIdResponses = {
    /**
     * Tâche récupérée
     */
    200: Task;
};

export type GetByIdResponse = GetByIdResponses[keyof GetByIdResponses];

export type UpdateData = {
    body: TaskRequest;
    path: {
        /**
         * Identifiant unique de la tâche à modifier (UUID)
         */
        id: string;
    };
    query?: never;
    url: '/api/tasks/{id}';
};

export type UpdateErrors = {
    /**
     * Données invalides
     */
    400: ApiResponse;
    /**
     * Utilisateur non authentifié
     */
    401: ApiResponse;
    /**
     * Tâche introuvable
     */
    404: ApiResponse;
    /**
     * Titre déjà utilisé
     */
    406: ApiResponse;
    /**
     * Internal Server Error
     */
    500: CustomApiResponseObject;
};

export type UpdateError = UpdateErrors[keyof UpdateErrors];

export type UpdateResponses = {
    /**
     * Tâche modifiée
     */
    200: Task;
};

export type UpdateResponse = UpdateResponses[keyof UpdateResponses];

export type ListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filtrer par statut
         */
        status?: 'BACKLOG' | 'TODO' | 'IN_PROGRESS' | 'IN_REVIEW' | 'BLOCKED' | 'ON_HOLD' | 'DONE' | 'CANCELLED';
        /**
         * Recherche textuelle sur le titre et la description
         */
        search?: string;
    };
    url: '/api/tasks';
};

export type ListErrors = {
    /**
     * Paramètre invalide
     */
    400: ApiResponse;
    /**
     * Utilisateur non authentifié
     */
    401: ApiResponse;
    /**
     * Not Found
     */
    404: CustomApiResponseObject;
    /**
     * Not Acceptable
     */
    406: CustomApiResponseObject;
    /**
     * Internal Server Error
     */
    500: CustomApiResponseObject;
};

export type ListError = ListErrors[keyof ListErrors];

export type ListResponses = {
    /**
     * Liste des tâches récupérée
     */
    200: Task;
};

export type ListResponse = ListResponses[keyof ListResponses];

export type CreateData = {
    body: TaskRequest;
    path?: never;
    query?: never;
    url: '/api/tasks';
};

export type CreateErrors = {
    /**
     * Données invalides
     */
    400: ApiResponse;
    /**
     * Utilisateur non authentifié
     */
    401: ApiResponse;
    /**
     * Not Found
     */
    404: CustomApiResponseObject;
    /**
     * Titre déjà utilisé
     */
    406: ApiResponse;
    /**
     * Internal Server Error
     */
    500: CustomApiResponseObject;
};

export type CreateError = CreateErrors[keyof CreateErrors];

export type CreateResponses = {
    /**
     * Tâche créée
     */
    201: Task;
};

export type CreateResponse = CreateResponses[keyof CreateResponses];

export type RegisterData = {
    body: UserRegisterRequest;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type RegisterErrors = {
    /**
     * Données invalides
     */
    400: CustomApiResponse;
    /**
     * Unauthorized
     */
    401: CustomApiResponseObject;
    /**
     * Not Found
     */
    404: CustomApiResponseObject;
    /**
     * Username déjà utilisé
     */
    406: CustomApiResponse;
    /**
     * Internal Server Error
     */
    500: CustomApiResponseObject;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * Utilisateur enregistré
     */
    201: CustomApiResponse;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type RefreshTokenData = {
    body: LogoutAndRefreshRequest;
    path?: never;
    query?: never;
    url: '/api/auth/refresh-token';
};

export type RefreshTokenErrors = {
    /**
     * Refresh token manquant ou mal formé
     */
    400: CustomApiResponse;
    /**
     * Refresh token expiré ou invalide
     */
    401: CustomApiResponse;
    /**
     * Not Found
     */
    404: CustomApiResponseObject;
    /**
     * Not Acceptable
     */
    406: CustomApiResponseObject;
    /**
     * Internal Server Error
     */
    500: CustomApiResponseObject;
};

export type RefreshTokenError = RefreshTokenErrors[keyof RefreshTokenErrors];

export type RefreshTokenResponses = {
    /**
     * Nouveau token généré
     */
    200: JwtAuthenticationResponse;
};

export type RefreshTokenResponse = RefreshTokenResponses[keyof RefreshTokenResponses];

export type LogoutData = {
    body: LogoutAndRefreshRequest;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutErrors = {
    /**
     * Bad Request
     */
    400: CustomApiResponseObject;
    /**
     * Utilisateur non authentifié
     */
    401: CustomApiResponse;
    /**
     * Not Found
     */
    404: CustomApiResponseObject;
    /**
     * Not Acceptable
     */
    406: CustomApiResponseObject;
    /**
     * Internal Server Error
     */
    500: CustomApiResponseObject;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * Déconnexion réussie
     */
    200: CustomApiResponse;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type LoginData = {
    body: UserLoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginErrors = {
    /**
     * Requête invalide
     */
    400: CustomApiResponse;
    /**
     * Identifiants invalides
     */
    401: CustomApiResponse;
    /**
     * Not Found
     */
    404: CustomApiResponseObject;
    /**
     * Not Acceptable
     */
    406: CustomApiResponseObject;
    /**
     * Internal Server Error
     */
    500: CustomApiResponseObject;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Authentification réussie
     */
    200: JwtAuthenticationResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type GetUserInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/user-info';
};

export type GetUserInfoErrors = {
    /**
     * Bad Request
     */
    400: CustomApiResponseObject;
    /**
     * Token manquant ou invalide
     */
    401: CustomApiResponse;
    /**
     * Not Found
     */
    404: CustomApiResponseObject;
    /**
     * Not Acceptable
     */
    406: CustomApiResponseObject;
    /**
     * Internal Server Error
     */
    500: CustomApiResponseObject;
};

export type GetUserInfoError = GetUserInfoErrors[keyof GetUserInfoErrors];

export type GetUserInfoResponses = {
    /**
     * Informations utilisateur récupérées
     */
    200: User;
};

export type GetUserInfoResponse = GetUserInfoResponses[keyof GetUserInfoResponses];
